POST http://localhost:3000/api/auth/user/register
Content-Type:application/json
{
    "firstName":"Ohm",
    "lastName":"Sonanis",
    "email":"ohm@gmail.com",
    "password":"ohm123"
}

POST http://localhost:3000/api/auth/user/login
Content-Type:application/json
{
    "email":"mayank@gmail.com",
    "password":"mayank123"
}

GET http://localhost:3000/api/auth/user/logout

POST http://localhost:3000/api/auth/admin/register
Content-Type:application/json
{
    "firstName":"Admin_1",
    "lastName":"Admin_1",
    "email":"admin1@gmail.com",
    "password":"admin1_123"

}

POST http://localhost:3000/api/auth/admin/login
Content-Type:application/json
{
    "email":"admin@gmail.com",
    "password":"admin123"

}

GET http://localhost:3000/api/auth/admin/logout

//Api to managee the products in cart
POST http://localhost:3000/api/cart/addToCart
Content-Type:application/json
{
    "action":   "ADD",
    "product":  "6a0064f21c84ad18ea2b07f0", 
    "name":     "Bamblonis",
    "image":    "https://ik.imagekit.io/mk8pjviaa/jayJhulelalBakery/premium_photo-1676573295464-cd20bfd68744_w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Ym9tYm9sb25pfGVufDB8fDB8fHww",
    "price":    400,
    "quantity": 1
}

//To get all cart items for user
POST http://localhost:3000/api/cart/
Content-Type:application/json
{
    "action":   "GET"
}

//To add remove Product from cart
POST http://localhost:3000/api/cart/removeProduct
Content-Type:application/json
{
    "action":   "REMOVE",
    "product":"6a0064f21c84ad18ea2b07f0"
}

//To add Clear CArt
POST http://localhost:3000/api/cart/removeProduct
Content-Type:application/json
{
    "action":   "CLEAR"
}


//Get All products 
GET http://localhost:3000/api/product/allProducts
https://jay-jhulelal-bakery.onrender.com/api/product/allProducts

//Get User By Id
GET http://localhost:3000/api/cart/getUserByToken

//ADD Order 
POST http://localhost:3000/api/order/placeOrder
Content-Type:application/json
{
    "items": [
        {
            "product": "6a0064f21c84ad18ea2b07f0",
            "name": "Bamblonis",
            "image": "https://...",
            "price": 400,
            "quantity": 2
        }
    ],
    "deliveryAddress": {
        "street": "8,sachin avenu",
        "city": "Anand",
        "pincode": "388001",
        "phone": "7203887396"
    }
}


//GET all Orders 
GET http://localhost:3000/api/order/getAllOrders

//Get all users(Customers)
GET http://localhost:3000/api/auth/admin/getAllUsers

//Populate users

GET http://localhost:3000/api/order/populateUsers

//Update isPaid Api
GET http://localhost:3000/api/order/updateIsPaid/6a0107529c4000c94b41ba94

//Update status
PUT http://localhost:3000/api/order/updateStatus/6a0107529c4000c94b41ba94
Content-Type:application/json
{
    "status":"Cancelled"
}

//Add New Product
POST http://localhost:3000/api/product/newProduct
Content-Type:application/json
{
    "name":"Muffin",
    "image":"https://ik.imagekit.io/mk8pjviaa/jayJhulelalBakery/photo-1557925923-6982bd9650ff_q=80&w=986&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA_3D_3D",
    "desc":"Golden, fluffy muffins crafted for a warm and indulgent experience in every bite.",
    "price":100,
    "qty":"piece",
    "rating":4,
    "reviews":100,
    "stock":90,
    "category":"cake",
    "isAvailable":true
}

//Update Product
PUT http://localhost:3000/api/product/updateProduct/6a05a85edac10bb96c9f86cc
Content-Type:application/json
{
    "name":"Muffin",
    "image":"https://ik.imagekit.io/mk8pjviaa/jayJhulelalBakery/photo-1557925923-6982bd9650ff_q=80&w=986&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA_3D_3D",
    "desc":"Golden, fluffy muffins crafted for a warm and indulgent experience in every bite.",
    "price":100,
    "qty":"piece",
    "rating":4,
    "reviews":100,
    "stock":90,
    "category":"cake",
    "isAvailable":true
}

//Delete Product
GET http://localhost:3000/api/product/deleteProduct/6a05a85edac10bb96c9f86cc

//low stock
GET http://localhost:3000/api/product/lowStock